#include "backend/qbe_frontend.h"

#include "backend/abstract_stack.h"
#include "backend/capture_analysis.h"
#include "backend/chunk_decoder.h"
#include "backend/qbe_emitter.h"
#include "compiler.h"
#include "exec_objects.h"
#include "memory_manager.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <sys/wait.h>
#include <unistd.h>

namespace {

// One function's RtFunctionDesc line, plus the QBE symbol the harness takes
// its address from. Mirrors tools/qbe_emit_program.cpp's stderr record.
struct CompiledFunction {
    std::string id;
    int arity;
    std::uint64_t chunkHash;
    std::string symbol;
};

std::string qbeSymbolFor(const std::string& id) {
    std::string sym = "lox_fn_" + id;
    for (char& c : sym) {
        if (c == '.') {
            c = '_';
        }
    }
    return sym;
}

void emitTree(const DecodedFunction& node,
              const StackAnalysisTree& analysisNode,
              const CaptureAnalysis& captures, const qbe::EmitOptions& options,
              std::string& ssa, std::vector<CompiledFunction>& fns) {
    std::string symbol = qbeSymbolFor(node.id);
    ssa += qbe::emitScript(node, analysisNode.self,
                           captures.functions.at(node.id), symbol, options);
    fns.push_back({node.id, node.function->arity,
                   hashChunkBytes(node.function->chunk), symbol});
    for (std::size_t i = 0; i < node.nested.size(); i++) {
        emitTree(node.nested[i], analysisNode.nested[i], captures, options, ssa,
                 fns);
    }
}

// Forks and execs `argv` directly. No shell, so paths need no quoting. The
// child's stdout/stderr are inherited, so qbe's and the linker's own
// diagnostics reach the user unchanged. Returns the child's exit status, or
// 127 when exec failed (program not found), matching a shell.
int runProcess(const std::vector<std::string>& argv) {
    std::vector<char*> c;
    c.reserve(argv.size() + 1);
    for (const std::string& a : argv) {
        c.push_back(const_cast<char*>(a.c_str()));
    }
    c.push_back(nullptr);

    pid_t pid = fork();
    if (pid < 0) {
        return -1;
    }
    if (pid == 0) {
        execvp(c[0], c.data());
        _exit(127);
    }
    int status = 0;
    if (waitpid(pid, &status, 0) < 0) {
        return -1;
    }
    if (WIFEXITED(status)) {
        return WEXITSTATUS(status);
    }
    return -1;
}

std::string makeTempDir() {
    std::error_code ec;
    std::filesystem::path base = std::filesystem::temp_directory_path(ec);
    if (ec) {
        return {};
    }
    std::string tmpl = (base / "loxpp-qbe-XXXXXX").string();
    std::vector<char> buf(tmpl.begin(), tmpl.end());
    buf.push_back('\0');
    char* made = mkdtemp(buf.data());
    if (made == nullptr) {
        return {};
    }
    return made;
}

std::string executableDir() {
    std::error_code ec;
    std::filesystem::path self =
        std::filesystem::read_symlink("/proc/self/exe", ec);
    if (ec) {
        return {};
    }
    return self.parent_path().string();
}

std::string resolveTool(const char* envName, const char* fallback) {
    const char* value = std::getenv(envName);
    if (value != nullptr && *value != '\0') {
        return value;
    }
    return fallback;
}

// A raw-string delimiter whose closing sequence cannot appear in `source`.
std::string rawDelimiter(const std::string& source) {
    std::string delim = "LOXPP_SRC_";
    while (source.find(")" + delim + "\"") != std::string::npos) {
        delim += "_";
    }
    return delim;
}

// The generated harness includes no project header: it declares only the
// small ABI it uses, so a release tarball needs to ship libloxrt.a but not
// the src/ include tree. rt_capi.cpp static_asserts the runtime side of that
// layout; an end-to-end CI step compiles and runs the harness to prove it.
std::string buildHarness(const std::string& source,
                         const std::vector<CompiledFunction>& fns) {
    std::string delim = rawDelimiter(source);
    std::ostringstream h;
    h << "// Generated by loxpp --target qbe. Do not edit.\n";
    h << "#include <cstddef>\n";
    h << "#include <cstdint>\n";
    h << "#include <string>\n\n";
    h << "extern \"C\" {\n";
    h << "struct RtFunctionDesc {\n";
    h << "    const char* id;\n";
    h << "    int arity;\n";
    h << "    std::uint64_t chunkHash;\n";
    h << "    void* code;\n";
    h << "};\n";
    h << "void* rt_startup(const char* source, const RtFunctionDesc* descs,\n";
    h << "                 std::size_t nDescs, bool requireAllCompiled);\n";
    h << "int rt_call(void* rt, int argCount, int stopAtFrameCount);\n";
    h << "void rt_shutdown(void* rt);\n";
    for (const CompiledFunction& f : fns) {
        h << "int " << f.symbol << "(void*, void*);\n";
    }
    h << "}\n\n";
    h << "static const char kSource[] = R\"" << delim << "(" << source << ")"
      << delim << "\";\n\n";
    h << "int main() {\n";
    h << "    RtFunctionDesc descs[] = {\n";
    for (const CompiledFunction& f : fns) {
        h << "        {\"" << f.id << "\", " << f.arity << ", "
          << static_cast<unsigned long long>(f.chunkHash)
          << "ULL, reinterpret_cast<void*>(&" << f.symbol << ")},\n";
    }
    h << "    };\n";
    h << "    void* rt = rt_startup(kSource, descs,\n";
    h << "                           sizeof(descs) / sizeof(descs[0]), "
         "true);\n";
    h << "    if (rt == nullptr) {\n";
    h << "        return 65;\n";
    h << "    }\n";
    h << "    int status = rt_call(rt, 0, 0);\n";
    h << "    rt_shutdown(rt);\n";
    h << "    return status == 0 ? 0 : 70;\n";
    h << "}\n";
    return h.str();
}

bool writeFile(const std::string& path, const std::string& contents) {
    std::ofstream out(path, std::ios::binary);
    if (!out) {
        return false;
    }
    out << contents;
    return static_cast<bool>(out);
}

} // namespace

int runQbeTarget(const std::string& exePath, const std::string& scriptPath,
                 bool noPromote, bool noFuse) {
    std::ifstream file(scriptPath);
    if (!file) {
        std::fprintf(stderr, "loxpp --target qbe: cannot read %s\n",
                     scriptPath.c_str());
        return 74;
    }
    std::stringstream ss;
    ss << file.rdbuf();
    std::string source = ss.str();

    MemoryManager mm;
    ObjFunction* script = compile(source, &mm);
    if (script == nullptr) {
        return 65;
    }

    qbe::EmitOptions options;
    options.promoteRegisters = !noPromote;
    options.fuseTagJumpTable = !noFuse;

    std::string ssa;
    std::vector<CompiledFunction> fns;
    try {
        DecodedFunction tree = decodeFunctionTree(script);
        StackAnalysisTree analysis = analyzeStackTree(tree);
        CaptureAnalysis captures = analyzeCaptures(tree);
        emitTree(tree, analysis, captures, options, ssa, fns);
    } catch (const std::exception& e) {
        std::fprintf(stderr, "loxpp --target qbe: %s\n", e.what());
        return 70;
    }

    std::string libPath;
    const char* envLib = std::getenv("LOX_RT_A");
    if (envLib != nullptr && *envLib != '\0') {
        libPath = envLib;
    } else {
        std::string dir = executableDir();
        if (!dir.empty()) {
            libPath = dir + "/libloxrt.a";
        }
    }
    if (libPath.empty() || !std::filesystem::exists(libPath)) {
        std::fprintf(stderr,
                     "loxpp --target qbe: libloxrt.a not found (set LOX_RT_A "
                     "or place it beside the loxpp binary)\n");
        return 74;
    }

    std::string work = makeTempDir();
    if (work.empty()) {
        std::fprintf(stderr, "loxpp --target qbe: cannot create a temporary "
                             "directory\n");
        return 74;
    }
    struct Cleanup {
        std::string dir;
        ~Cleanup() {
            std::error_code ec;
            std::filesystem::remove_all(dir, ec);
        }
    } cleanup{work};

    std::string ssaPath = work + "/prog.ssa";
    std::string asmPath = work + "/prog.s";
    std::string harnessPath = work + "/harness.cpp";
    if (!writeFile(ssaPath, ssa) ||
        !writeFile(harnessPath, buildHarness(source, fns))) {
        std::fprintf(stderr,
                     "loxpp --target qbe: cannot write files under %s\n",
                     work.c_str());
        return 74;
    }

    std::string qbeBin = resolveTool("QBE", "qbe");
    int rc = runProcess({qbeBin, "-o", asmPath, ssaPath});
    if (rc != 0) {
        if (rc == 127) {
            std::fprintf(stderr,
                         "loxpp --target qbe: '%s' not found (set QBE)\n",
                         qbeBin.c_str());
        } else {
            std::fprintf(stderr, "loxpp --target qbe: qbe failed on %s\n",
                         scriptPath.c_str());
        }
        return 70;
    }

    // Prefer CXX, then c++, then cc. A 127 (not found) advances to the next
    // candidate; any other failure is a real link/compile error and stops.
    std::vector<std::string> compilers;
    const char* envCxx = std::getenv("CXX");
    if (envCxx != nullptr && *envCxx != '\0') {
        compilers.emplace_back(envCxx);
    } else {
        compilers.emplace_back("c++");
        compilers.emplace_back("cc");
    }
    rc = 127;
    for (const std::string& compiler : compilers) {
        rc = runProcess({compiler, "-std=c++17", "-O2", harnessPath, asmPath,
                         libPath, "-lstdc++", "-lm", "-o", exePath});
        if (rc != 127) {
            break;
        }
    }
    if (rc == 127) {
        std::fprintf(stderr,
                     "loxpp --target qbe: no C++ compiler found (set CXX)\n");
        return 70;
    }
    if (rc != 0) {
        std::fprintf(stderr, "loxpp --target qbe: link failed\n");
        return 70;
    }
    return 0;
}
