<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lox</string>
	</array>
	<key>name</key>
	<string>Lox++</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators-patterns</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifiers</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lox</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=$)</string>
			<key>name</key>
			<string>comment.line.double-slash.lox</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(TODO|FIXME)\b</string>
					<key>name</key>
					<string>keyword.comment.todo.lox</string>
				</dict>
			</array>
		</dict>
		<key>declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.lox</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.lox</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.inheritance.lox</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.lox</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(class)\s+([a-zA-Z_]\w*)(?:\s*(&lt;)\s*([a-zA-Z_]\w*))?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.lox</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.lox</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(fun)\s+([a-zA-Z_]\w*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.lox</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.enum.lox</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(enum)\s+([a-zA-Z_]\w*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.lox</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?!if\b|else\b|for\b|while\b|return\b|print\b|catch\b|case\b|var\b|fun\b|class\b|enum\b|try\b|defer\b|throw\b|match\b|this\b|super\b|default\b|and\b|or\b|in\b|true\b|false\b|nil\b|break\b|continue\b)([a-zA-Z_]\w*)(?=\s*\()</string>
				</dict>
			</array>
		</dict>
		<key>identifiers</key>
		<dict>
			<key>match</key>
			<string>\b[a-zA-Z_]\w*\b</string>
			<key>name</key>
			<string>variable.other.lox</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:true|false|nil)\b</string>
					<key>name</key>
					<string>constant.language.lox</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:and|or|in)\b</string>
					<key>name</key>
					<string>keyword.operator.logical.lox</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:class|fun|var|enum)\b</string>
					<key>name</key>
					<string>storage.type.lox</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:if|else|for|while|break|continue|return|print)\b</string>
					<key>name</key>
					<string>keyword.control.lox</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:match|case)\b</string>
					<key>name</key>
					<string>keyword.control.match.lox</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:default|this|super)\b</string>
					<key>name</key>
					<string>keyword.control.lox</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:try|catch|throw|defer)\b</string>
					<key>name</key>
					<string>keyword.control.exception.lox</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z_0-9])[0-9]+(?:\.[0-9]+)?</string>
			<key>name</key>
			<string>constant.numeric.lox</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>=&gt;|==|!=|&lt;=|&gt;=|[=+\-*/%&lt;&gt;!]</string>
			<key>name</key>
			<string>keyword.operator.lox</string>
		</dict>
		<key>operators-patterns</key>
		<dict>
			<key>match</key>
			<string>@|\.\.\.</string>
			<key>name</key>
			<string>keyword.operator.pattern.lox</string>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[()\[\]{}]</string>
					<key>name</key>
					<string>punctuation.section.brackets.lox</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[,;:]</string>
					<key>name</key>
					<string>punctuation.separator.lox</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>punctuation.separator.dot.lox</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.lox</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.lox</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.lox</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\["\\ntr0]</string>
							<key>name</key>
							<string>constant.character.escape.lox</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal.bad-escape.lox</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lox</string>
	<key>uuid</key>
	<string>91cde506-f7e5-4758-8630-31880a512525</string>
</dict>
</plist>
