package lox;

/**
 * Base class for every generated function/method body. Holds the upvalue
 * cells captured at CLOSURE time — one {@code Object[1]} ref-cell per
 * upvalue, matching the fresh-cell-per-declaration model in
 * bytecode-translation-problems.md (P4): CLOSE_UPVALUE ends a cell's live
 * range, it does not merely no-op.
 *
 * Lox slot 0 is "the callee itself — or, in a method, the receiver `this`"
 * (same doc, root-cause section). {@link #call} binds slot 0 to this closure,
 * matching a plain function reading its own identity; {@link #callAsSelf}
 * lets a bound-method/INVOKE/SUPER_INVOKE call site bind slot 0 to the
 * receiver instead. `arity` excludes slot 0, matching ObjFunction::arity.
 */
public abstract class LoxClosure implements LoxCallable {
    // Mirrors src/vm.h's FRAMES_MAX and runtime/clr/src/LoxClosure.cs's own
    // FramesMax. Generated bytecode recurses the real JVM call stack one
    // frame per Lox call — unlike vm.cpp's fixed CallFrame array, nothing
    // here bounds that on its own, and the real stack tolerates far more
    // than 1024 nested calls (tools/jvm_run.sh runs with -Xss64m by
    // default) before it would fault. Counting here keeps every recursion
    // depth native accepts or rejects agreeing on the JVM backend too, with
    // the same message, instead of only diverging once a real stack fault
    // (an uncatchable java.lang.StackOverflowError) hits some larger,
    // host-dependent depth.
    //
    // Native has a second ceiling this counter does not mirror: src/vm.h's
    // STACK_MAX (16384 value-stack slots, shared by every live frame) can
    // be reached by a frame with many locals well below 1024 calls deep.
    // A program that overflows only STACK_MAX on native still runs to
    // completion here — a known, open gap, not a native defect (see
    // test/translation-probes/clr-only/known-divergence's header for the
    // CLR backend's identical gap).
    private static final int FRAMES_MAX = 1024;

    // Mirrors src/vm.h's STACK_OVERFLOW_FRAME_RESERVE. Spent only while a
    // StackOverflowError this class raised is still unwinding
    // (s_unwindingStackOverflow below): a deferred call drained during that
    // unwind runs before the JVM's own call-stack unwind has brought
    // s_frameCount back down past FRAMES_MAX, so it needs room of its own
    // to make any nested calls at all — the same reason native reserves
    // capacity above its own FRAMES_MAX instead of using one ceiling for
    // both the ordinary and the unwinding case.
    private static final int FRAMES_RESERVE = 16;

    // Starts at 1, not 0: src/vm.cpp's own interpret() pushes the
    // top-level script itself as CallFrame 0 through the very same call()
    // this class's CallAsSelf mirrors, before the script body ever runs,
    // and that frame is never popped until the whole program ends. A
    // counter starting at 0 here would let one more nested Lox call
    // succeed than FRAMES_MAX allows natively.
    private static int s_frameCount = 1;

    // True for the dynamic extent between a StackOverflowError this class
    // raises and that same fault's resolution (delivered to a real
    // try/catch, or the program exiting fatally) — LoxError's own
    // getValue() clears this the moment it delivers the fault s_overflowInFlight
    // still names, which is the only point that knows the unwind is over.
    // A second overflow raised inside that extent — reachable only through
    // a deferred call that itself recurses too deep while running during
    // the first overflow's own unwind — is not delivered to any catchBlock
    // (spec/04-semantics.md line 1120); it is fatal, matching native's own
    // m_unwindingStackOverflow guard (src/vm.h).
    private static boolean s_unwindingStackOverflow = false;

    // The LoxError object whose delivery to getValue() ends the unwind
    // above. Starts as the StackOverflowError this class raises.
    // spec/04-semantics.md's defer Statement step 5 lets a deferred call's
    // own throw, if not caught within it, replace whatever fault was
    // already propagating through the frame draining that defer; when that
    // happens, LoxOps.runDefers() calls replaceOverflowInFlight() so this
    // field tracks the replacement instead, but only when the replaced
    // fault is the one this guard already names. Identity, not the
    // delivered value's own kind field, is what must decide the unwind is
    // over: a plain Lox++ instance can carry a field named "kind" equal to
    // "StackOverflowError" with no connection to this guard at all, and a
    // kind-string check would clear the guard on that alone.
    private static LoxError s_overflowInFlight = null;

    public final String name; // null for the top-level script, per <script>
    public final int arity;
    public final Object[][] upvalues;

    protected LoxClosure(String name, int arity, Object[][] upvalues) {
        this.name = name;
        this.arity = arity;
        this.upvalues = upvalues;
    }

    @Override
    public final Object call(Object[] args) {
        return callAsSelf(this, args);
    }

    public final Object callAsSelf(Object self, Object[] args) {
        if (args.length != arity) {
            // src/vm.cpp VM::call() makes ArityError catchable only when a
            // handler is live somewhere in the program; with none live, it
            // calls runtimeError() directly, bypassing the catchable
            // machinery entirely (issue #319). LoxOps.isHandlerLive()
            // mirrors that same dynamic (call-stack-dependent, not
            // per-call-site) test.
            if (!LoxOps.isHandlerLive()) {
                throw new LoxError(
                        "Expected " + arity + " arguments but got " + args.length + ".");
            }
            throw LoxOps.makeError("ArityError",
                    "Expected " + arity + " arguments but got " + args.length + ".");
        }
        if (s_unwindingStackOverflow) {
            // Already unwinding one StackOverflowError: only the reserve
            // stands between here and fatal, and no further catchable
            // attempt is made (see s_unwindingStackOverflow's own comment).
            if (s_frameCount >= FRAMES_MAX + FRAMES_RESERVE) {
                // A raw, valueless LoxError is uncatchable: LoxError.getValue()
                // rethrows it instead of delivering it to any catchBlock.
                throw new LoxError("Stack overflow.");
            }
        } else if (s_frameCount >= FRAMES_MAX) {
            if (!LoxOps.isHandlerLive()) {
                // src/vm.cpp VM::call() takes the same fatal fast path (no
                // handler live anywhere in the program) for the first
                // overflow too — it never constructs the catchable
                // StackOverflowError Error value in that case (issue
                // #319). s_unwindingStackOverflow stays false: this fault
                // is never delivered, so there is no unwind for a second
                // overflow to be re-entrant with.
                throw new LoxError("Stack overflow.");
            }
            s_unwindingStackOverflow = true;
            LoxError overflow =
                    LoxOps.makeError("StackOverflowError", "Stack overflow.");
            s_overflowInFlight = overflow;
            throw overflow;
        }
        s_frameCount++;
        try {
            return invoke(self, args);
        } finally {
            s_frameCount--;
        }
    }

    // Package-private: LoxError.getValue() calls this, and only this,
    // exactly when the fault it is about to deliver to a real catchBlock is
    // the one s_overflowInFlight names. Resetting there — not at throw
    // time — is what lets a deferred call spend the reserve above while
    // this fault is still propagating, without a later, unrelated overflow
    // being mistaken for part of the same unwind.
    static void endStackOverflowUnwind() {
        s_unwindingStackOverflow = false;
        s_overflowInFlight = null;
    }

    // Package-private: LoxError.getValue() calls this to decide whether IT
    // is the fault whose delivery ends the current unwind (see
    // s_overflowInFlight's own comment) — by identity, not by inspecting
    // the delivered value.
    static boolean isOverflowInFlight(LoxError error) {
        return s_unwindingStackOverflow && error == s_overflowInFlight;
    }

    // Package-private: LoxOps.runDefers() calls this when a deferred call's
    // own throw escapes it (spec/04-semantics.md defer Statement step 5),
    // passing the exact fault this defer list is being drained for. The
    // guard's identity moves only when `replaced` names the fault it
    // already watches — not merely whenever the guard happens to be
    // active — so a defer that throws on a normal return, or that replaces
    // some other, unrelated fault while an overflow unwinds elsewhere,
    // leaves this guard untouched. Only the generated exceptional-path
    // handler knows which fault a defer list is being drained for, so it
    // is the one caller that can supply `replaced` correctly.
    static void replaceOverflowInFlight(LoxError replaced, LoxError replacement) {
        if (s_unwindingStackOverflow && replaced == s_overflowInFlight) {
            s_overflowInFlight = replacement;
        }
    }

    protected abstract Object invoke(Object self, Object[] args);
}
