#!/usr/bin/env bash
#
# Round-trips a trivial program through each managed toolchain in the
# dev-managed image. Its purpose is diagnostic isolation: once the JVM and CLR
# backends exist, a failure here means the image is broken or version-skewed,
# and a failure there means the generated bytecode is wrong. Without it, the
# first backend commit debugs both at once.
#
# Also prints exact toolchain versions, since HotSpot and RyuJIT versions are
# part of any performance baseline measured through these backends.
set -euo pipefail

fixtures="$(cd "$(dirname "${BASH_SOURCE[0]}")/toolchain_smoke" && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

failures=0

check() {
    local name="$1" expected="$2" actual="$3"
    if [ "$actual" = "$expected" ]; then
        printf '  ok    %s\n' "$name"
    else
        printf '  FAIL  %s\n          expected: %s\n          actual:   %s\n' \
            "$name" "$expected" "$actual"
        failures=$((failures + 1))
    fi
}

# Jasmin and ilasm print their banner and exit nonzero when invoked with no
# arguments, so these probes must not be allowed to trip `set -e` — the banner
# is what we are after, not the status.
echo "== toolchain versions =="
java -version 2>&1 | sed 's/^/  /' || true
printf '  javac %s\n' "$(javac -version 2>&1 | awk '{print $2}' || true)"
printf '  jasmin %s\n' \
    "$(java -jar /opt/jasmin/jasmin.jar -version 2>&1 | awk '/Jasmin/ {print $3; exit}' || true)"
printf '  jasmin emits class file version %s\n' \
    "$(cd "$work" && jasmin -d . "$fixtures/hello.j" >/dev/null 2>&1 \
        && javap -v HelloJasmin.class 2>/dev/null \
        | awk '/major version/ {maj = $3} /minor version/ {min = $3} END {print maj "." min}' \
        || true)"
printf '  dotnet sdk %s\n' "$(dotnet --version || true)"
printf '  ilasm %s\n' \
    "$(ilasm -? 2>&1 | awk '/IL Assembler/ {print $NF; exit}' || true)"

echo
echo "== round-trips =="

# 1. JDK alone — isolates a broken JDK from a broken Jasmin.
cp "$fixtures/Hello.java" "$work/"
(cd "$work" && javac Hello.java)
check "javac -> java" "javac ok" "$(cd "$work" && java Hello)"

# 2. Jasmin: the path the JVM backend emits into.
cp "$fixtures/hello.j" "$work/"
(cd "$work" && jasmin -d . hello.j >/dev/null)
check "jasmin -> java" "jasmin ok" "$(cd "$work" && java HelloJasmin)"

# 2b. Branching bytecode. Guards the assumption the backend rests on: that it
#     never has to compute a StackMapTable. That holds only because Jasmin emits
#     class file 45.3, below the version where frames became mandatory — so this
#     verifying is the real evidence, not the straight-line case above.
cp "$fixtures/branch.j" "$work/"
(cd "$work" && jasmin -d . branch.j >/dev/null)
check "jasmin -> java (branching)" "branching ok" "$(cd "$work" && java BranchProbe)"

# 3. ilasm: the path the CLR backend emits into. Two Linux-specific traps here,
#    both of which the backend's build step will hit as well:
#    - Options need `-`, not `/`. Given `/exe`, ilasm reads an absolute path and
#      tries to assemble a file named /exe.il, then reports FAILURE.
#    - A raw ilasm assembly has no runtimeconfig.json, and `dotnet` refuses to
#      run an assembly without one, so it has to be generated.
cp "$fixtures/hello.il" "$work/"
(cd "$work" && ilasm -exe -output:HelloIl.dll hello.il >/dev/null)
runtime_version="$(dotnet --list-runtimes \
    | awk '$1 == "Microsoft.NETCore.App" { v = $2 } END { print v }')"
cat > "$work/HelloIl.runtimeconfig.json" <<JSON
{
  "runtimeOptions": {
    "tfm": "net8.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "${runtime_version}"
    }
  }
}
JSON
check "ilasm -> dotnet" "ilasm ok" "$(cd "$work" && dotnet HelloIl.dll)"

echo
if [ "$failures" -ne 0 ]; then
    echo "$failures managed toolchain check(s) failed."
    exit 1
fi
echo "All managed toolchain checks passed."
