#!/usr/bin/env bash
#
# Round-trips a trivial program through each managed toolchain in the
# dev-managed image. Its purpose is diagnostic isolation: once the JVM and CLR
# backends exist, a failure here means the image is broken or version-skewed,
# and a failure there means the generated bytecode is wrong. Without it, the
# first backend commit debugs both at once.
#
# Also prints exact toolchain versions, since HotSpot and RyuJIT versions are
# part of any performance baseline measured through these backends.
set -euo pipefail

fixtures="$(cd "$(dirname "${BASH_SOURCE[0]}")/toolchain_smoke" && pwd)"
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

failures=0

check() {
    local name="$1" expected="$2" actual="$3"
    if [ "$actual" = "$expected" ]; then
        printf '  ok    %s\n' "$name"
    else
        printf '  FAIL  %s\n          expected: %s\n          actual:   %s\n' \
            "$name" "$expected" "$actual"
        failures=$((failures + 1))
    fi
}

# Compile and assemble steps have to report through the same path as everything
# else. As bare commands under `set -e` they abort the script before `check` runs,
# so a broken assembler — the failure mode that produces the least output — would
# surface as a bare nonzero exit. Output is captured and printed only on failure:
# ilasm writes its errors to stdout, so discarding it would throw away the only
# explanation of what went wrong.
step() {
    local name="$1"; shift
    local out
    if out="$("$@" 2>&1)"; then
        return 0
    fi
    printf '  FAIL  %s\n' "$name"
    printf '%s\n' "$out" | sed 's/^/          /'
    failures=$((failures + 1))
    return 1
}

cd "$work"
cp "$fixtures/Hello.java" "$fixtures/hello.j" "$fixtures/branch.j" \
   "$fixtures/hello.il" "$fixtures/hello_rt.il" .

# Jasmin and ilasm print their banner and exit nonzero when invoked with no
# arguments, so these probes must not be allowed to trip `set -e` — the banner
# is what we are after, not the status.
echo "== toolchain versions =="
java -version 2>&1 | sed 's/^/  /' || true
printf '  javac %s\n' "$(javac -version 2>&1 | awk '{print $2}' || true)"
printf '  jasmin %s\n' \
    "$(java -jar /opt/jasmin/jasmin.jar -version 2>&1 | awk '/Jasmin/ {print $3; exit}' || true)"
printf '  dotnet sdk %s\n' "$(dotnet --version || true)"
printf '  ilasm %s\n' \
    "$(ilasm -? 2>&1 | awk '/IL Assembler/ {print $NF; exit}' || true)"

# Pick the highest runtime rather than whichever awk saw last, and derive the tfm
# from it: hardcoding one while discovering the other would silently pair a 9.0
# framework with a net8.0 tfm if a second runtime ever lands in the image.
runtime_version="$(dotnet --list-runtimes 2>/dev/null \
    | awk '$1 == "Microsoft.NETCore.App" { print $2 }' | sort -V | tail -1 || true)"
printf '  dotnet runtime %s\n' "${runtime_version:-<none found>}"

echo
echo "== round-trips =="

# 1. JDK alone — isolates a broken JDK from a broken Jasmin.
if step "javac" javac Hello.java; then
    check "javac -> java" "javac ok" "$(java Hello 2>&1 || true)"
fi

# 2. Jasmin: the path the JVM backend emits into.
if step "jasmin assembly" jasmin -d . hello.j; then
    check "jasmin -> java" "jasmin ok" "$(java HelloJasmin 2>&1 || true)"

    # Asserted, not merely logged: both backend plans rest on this version
    # staying below the frame requirement, so it should fail loudly rather than
    # print a number nothing reads.
    check "jasmin class file version" "45.3" \
        "$(javap -v HelloJasmin.class 2>/dev/null \
            | awk '/major version/ {maj = $3} /minor version/ {min = $3}
                   END {print maj "." min}' || true)"
fi

# 2b. Branching bytecode — the case that actually bears on frames. A v51+ class
#     file with these branches and no StackMapTable fails verification outright;
#     at exactly v50 HotSpot still fails over to the old type-inferencing
#     verifier, so v51 is where this check starts biting. 45.3 sits below both.
if step "jasmin assembly (branching)" jasmin -d . branch.j; then
    check "jasmin -> java (branching)" "branching ok" \
        "$(java BranchProbe 2>&1 || true)"
fi

# 2c. lox-rt link: a hand-written class calls lox.LoxOps.print and links
# against lox-rt.jar, through tools/jvm_run.sh — the same harness a code
# generator will call. This proves the assemble -> run -> link chain end to
# end, before any code generator exists. Run through jvm_run.sh itself, not a
# second copy of its jasmin/java calls, so a regression there shows up here
# too. Must fail loudly, not skip, when the jar is missing: a passing check
# must mean the link happened, not that it was never attempted.
mkdir -p hellort
cp "$fixtures/HelloRt.j" hellort/
check "jvm_run.sh -> java (lox-rt link)" "lox-rt ok" \
    "$("$repo_root/tools/jvm_run.sh" hellort "$repo_root/runtime/jvm/lox-rt.jar" HelloRt 2>&1 || true)"

# 3. ilasm: the path the CLR backend emits into. Two Linux-specific traps here,
#    both of which the backend's build step will hit as well:
#    - Options need `-`, not `/`. Given `/exe`, ilasm reads an absolute path and
#      tries to assemble a file named /exe.il, then reports FAILURE.
#    - A raw ilasm assembly has no runtimeconfig.json, and `dotnet` refuses to
#      run an assembly without one, so it has to be generated.
if [ -z "$runtime_version" ]; then
    printf '  FAIL  dotnet runtime discovery (no Microsoft.NETCore.App listed)\n'
    failures=$((failures + 1))
elif step "ilasm assembly" ilasm -exe -output:HelloIl.dll hello.il; then
    cat > HelloIl.runtimeconfig.json <<JSON
{
  "runtimeOptions": {
    "tfm": "net${runtime_version%%.*}.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "${runtime_version}"
    }
  }
}
JSON
    check "ilasm -> dotnet" "ilasm ok" "$(dotnet HelloIl.dll 2>&1 || true)"
fi

# 3b. CLR lox-rt link: a hand-written class calls Lox.LoxOps.Print and links
# against LoxRuntime.dll — the CLR counterpart of 2c above. This proves the
# assemble -> run -> link chain end to end, before any code generator
# exists. Must fail loudly, not skip, when the DLL is missing: a passing
# check must mean the link happened, not that it was never attempted.
lox_rt_dll="$repo_root/runtime/clr/LoxRuntime.dll"
if [ ! -f "$lox_rt_dll" ]; then
    printf '  FAIL  clr lox-rt link (no such runtime dll: %s)\n' "$lox_rt_dll"
    printf '          run tools/build_lox_rt_clr.sh first\n'
    failures=$((failures + 1))
elif [ -z "$runtime_version" ]; then
    printf '  FAIL  clr lox-rt link (no dotnet runtime discovered; see the ilasm check above)\n'
    failures=$((failures + 1))
elif step "ilasm assembly (lox-rt link)" ilasm -exe -output:HelloRt.dll hello_rt.il; then
    cp "$lox_rt_dll" .
    cat > HelloRt.runtimeconfig.json <<JSON
{
  "runtimeOptions": {
    "tfm": "net${runtime_version%%.*}.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "${runtime_version}"
    }
  }
}
JSON
    check "ilasm -> dotnet (lox-rt link)" "lox-rt ok" "$(dotnet HelloRt.dll 2>&1 || true)"
fi

echo
if [ "$failures" -ne 0 ]; then
    echo "$failures managed toolchain check(s) failed."
    exit 1
fi
echo "All managed toolchain checks passed."
