#!/bin/bash
# run_stages.sh — public-source test oracle for the Lox++ SQLite reader.
#
# Base stages 1-8 are transcribed from codecrafters-io/build-your-own-sqlite
# stage_descriptions/base-*.md (public, no membership needed), run against
# the fixtures generated by gen_fixtures.py in place of the challenge's own
# non-public sample.db/superheroes.db. Stage 9 (index scan) is not
# implemented — see README.md.
#
# Usage: tests/run_stages.sh [your_sqlite.sh]
PROG="${1:-$(dirname "$0")/../your_sqlite.sh}"
case "$PROG" in
    /*) ;;
    *) PROG="$(cd "$(dirname "$0")/.." && pwd)/your_sqlite.sh" ;;
esac
HERE="$(cd "$(dirname "$0")" && pwd)"
SAMPLE="$HERE/fixtures/sample.db"
SUPERHEROES="$HERE/fixtures/superheroes.db"
PASS=0
FAIL=0

# check <name> <expected-stdout> -- args...
check() {
    local name="$1" want_out="$2"
    shift 2
    local got_out got_rc
    got_out=$("$PROG" "$@" 2>/dev/null)
    got_rc=$?
    if [ "$got_rc" = 0 ] && [ "$got_out" = "$want_out" ]; then
        PASS=$((PASS + 1))
    else
        FAIL=$((FAIL + 1))
        printf 'FAIL %s\n  args: %s\n  want rc=0 out=%q\n  got  rc=%s out=%q\n' \
            "$name" "$*" "$want_out" "$got_rc" "$got_out"
    fi
}

# ---- base-01-dr6: .dbinfo page size ----
check "dbinfo-page-size" "$(printf 'database page size: 4096\nnumber of tables: 3')" \
    "$SAMPLE" .dbinfo

# ---- base-03-sz4: .tables (sqlite_sequence, an internal table from the
# AUTOINCREMENT columns below, is filtered like real sqlite3's .tables) ----
check "tables" "apples oranges" "$SAMPLE" .tables

# ---- base-04-nd9: SELECT COUNT(*) ----
check "count" "4" "$SAMPLE" "SELECT COUNT(*) FROM apples"

# ---- base-05-az9: single column ----
check "select-one-col" "$(printf 'Granny Smith\nFuji\nHoneycrisp\nGolden Delicious')" \
    "$SAMPLE" "SELECT name FROM apples"

# ---- base-06-vc9: multiple columns ----
check "select-two-cols" "$(printf 'Granny Smith|Light Green\nFuji|Red\nHoneycrisp|Blush Red\nGolden Delicious|Yellow')" \
    "$SAMPLE" "SELECT name, color FROM apples"

# ---- base-07-rf3: WHERE equality ----
check "where" "Golden Delicious|Yellow" \
    "$SAMPLE" "SELECT name, color FROM apples WHERE color = 'Yellow'"

# ---- rowid alias (INTEGER PRIMARY KEY AUTOINCREMENT is stored as NULL;
# the real value comes from the cell's rowid) ----
check "rowid-alias" "$(printf '1|Mandarin\n2|Navel\n3|Blood Orange')" \
    "$SAMPLE" "SELECT id, name FROM oranges"

# ---- base-08-ws9: multi-page table b-tree + WHERE (superheroes.db is
# ~130KB / 32 pages here vs. the challenge's ~1MB; same interior/leaf
# traversal path) ----
check "multi-page-count" "3000" "$SUPERHEROES" "SELECT COUNT(*) FROM superheroes"

got_out=$("$PROG" "$SUPERHEROES" "SELECT id, name FROM superheroes WHERE eye_color = 'Pink Eyes'" 2>/dev/null | LC_ALL=C sort -t'|' -k1,1n)
got_rc=$?
want_lines=515
got_lines=$(printf '%s\n' "$got_out" | wc -l | tr -d ' ')
if [ "$got_rc" = 0 ] && [ "$got_lines" = "$want_lines" ]; then
    PASS=$((PASS + 1))
else
    FAIL=$((FAIL + 1))
    printf 'FAIL multi-page-where\n  want %s rows, got rc=%s rows=%s\n' "$want_lines" "$got_rc" "$got_lines"
fi

printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
